// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppStartProjeto1.Models
{
    public partial class Pessoa
    {
        [Key]
        public int Id { get; set; }
        public int? Idade { get; set; }
        [StringLength(14)]
        [Unicode(false)]
        public string Cpf { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
    }
}