// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppStartProjeto1.Models
{
    public partial class Veiculos
    {
        public int? Ano { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("valorFipe", TypeName = "decimal(18, 2)")]
        public decimal? ValorFipe { get; set; }
        [Key]
        [Column("id")]
        public int Id { get; set; }
    }
}